### ISSUE TITLE
Training from scracth

### ISSUE THREAD

**Issue by kame5** [santi-pdp/pase#113]
I would train pase model from scratch. 
I have 2 main issue.
1.how to solve warning
"""
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
"""
2.how to solve stop Iteration.
Did I do something wrong?
"""
Traceback (most recent call last):
  File "E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master\pase\models\WorkerScheduler\trainer.py", line 295, in _eval
    batch = next(iterator)
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 465, in <module>
    train(opts)
  File "train.py", line 333, in train
    Trainer.train_(dloader, device=device, valid_dataloader=va_dloader)
  File "E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master\pase\models\WorkerScheduler\trainer.py", line 265, in train_
    device=device)
  File "E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master\pase\models\WorkerScheduler\trainer.py", line 298, in _eval
    batch = next(iterator)
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration

"""
Thanks in advance for any help that you are able to provide.

(pase-master) E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master>python -u train.py --batch_size 32 --epoch 150 --save_path pase_ckpt --num_workers 4 --net_cfg cfg/workers/workers.cfg --fe_cfg cfg/frontend/PASE.cfg --data_cfg data/librispeech_data.cfg --min_lr 0.0005 --fe_lr 0.0005 --data_root E:/SpeechEmotionDataSet/ThaiEmotionDB --stats data/librispeech_stats.pkl --lrdec_step 30 --lrdecay 0.5
################################################################################
################################################################################

[!] Using CPU
Seeds initialized to 2
{'regr': [{'num_outputs': 1, 'dropout': 0, 'hidden_layers': 1, 'name': 'cchunk', 'type': 'decoder', 'hidden_size': 64, 'fmaps': [512, 256, 128], 'strides': [4, 4, 10], 'kwidths': [30, 30, 30], 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFDC8DF208>}, {'num_outputs': 1025, 'dropout': 0, 'hidden_size': 256, 'hidden_layers': 1, 'name': 'lps', 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFDC8DF108>, 'transform': {'der_order': 0}, 'skip': False}, {'num_outputs': 20, 'dropout': 0, 'hidden_size': 256, 'hidden_layers': 1, 'name': 'mfcc', 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFDC8DF2C8>, 'transform': {'der_order': 0, 'order': 20}, 'skip': False}, {'num_outputs': 4, 'dropout': 0, 'hidden_size': 256, 'hidden_layers': 1, 'name': 'prosody', 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFDC8DF308>, 'transform': {'der_order': 0}, 'skip': False}], 'cls': [{'num_outputs': 1, 'dropout': 0, 'hidden_size': 256, 'hidden_layers': 1, 'name': 'spc', 'type': 'spc', 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFD9C3EAC8>, 'skip': False}, {'num_outputs': 1, 'dropout': 0, 'hidden_size': 256, 'hidden_layers': 1, 'name': 'mi', 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFDC8DF408>, 'skip': False, 'keys': ['chunk', 'chunk_ctxt', 'chunk_rand']}, {'num_outputs': 1, 'dropout': 0, 'hidden_size': 256, 'hidden_layers': 1, 'name': 'cmi', 'loss': <pase.losses.ContextualizedLoss object at 0x000001CFDC8DF4C8>, 'skip': False, 'keys': ['chunk', 'chunk_ctxt', 'chunk_rand']}]}
Compose(
    ToTensor()
    MIChunkWav(16000)
    LPS(n_fft=2048, hop=160, win=400, device=cpu)
    MFCC(order=20, sr=16000)
    Prosody(hop=160, win=320, f0_min=60, f0_max=300, sr=16000)
    ZNorm(data/librispeech_stats.pkl)
)
Preparing dset for E:/SpeechEmotionDataSet/ThaiEmotionDB
Dataset name <class 'pase.dataset.LibriSpeechSegTupleWavDataset'> and opts LibriSpeechSegTupleWavDataset
Found 2 speakers info
Found 91 files in train split
Found 2 speakers in train split
Found 2 prefixes in utterances
Found 2 speakers info
Found 10 files in valid split
Found 0 speakers in valid split
Found 2 prefixes in utterances
Dataset has a total 0.11004553819444443 hours of training data
<_io.TextIOWrapper name='cfg/frontend/PASE.cfg' mode='r' encoding='cp1252'>
{'kwidths': [251, 20, 11, 11, 11, 11, 11, 11], 'strides': [1, 10, 2, 1, 2, 1, 2, 2], 'fmaps': [64, 64, 128, 128, 256, 256, 512, 512], 'emb_dim': 100, 'norm_out': True}
True
Cls:  ['spc', 'mi', 'cmi']
Regr:  ['cchunk', 'lps', 'mfcc', 'prosody']
training pase...
pase config ==> {'kwidths': [251, 20, 11, 11, 11, 11, 11, 11], 'strides': [1, 10, 2, 1, 2, 1, 2, 2], 'fmaps': [64, 64, 128, 128, 256, 256, 512, 512], 'emb_dim': 100, 'norm_out': True}
==>concat features from 1 levels
==>input size for workers: 100
==================================================
name cchunk
==================================================
Dropout at the inputs disabled, as p=0
==================================================
name lps
==================================================
Dropout at the inputs disabled, as p=0.0
==================================================
name mfcc
==================================================
Dropout at the inputs disabled, as p=0.0
==================================================
name prosody
==================================================
Dropout at the inputs disabled, as p=0.0
==================================================
name spc
==================================================
==================================================
name spc
==================================================
num_inputs:  100
ctxt_frames:  5
num_inputs:  600
Dropout at the inputs disabled, as p=0.0
==================================================
name mi
==================================================
==================================================
name mi
==================================================
Dropout at the inputs disabled, as p=0.0
==================================================
name cmi
==================================================
==================================================
name cmi
==================================================
Dropout at the inputs disabled, as p=0.0
Using step LR Scheduler for frontend!
Using step LR Scheduler for spc!
Using step LR Scheduler for mi!
Using step LR Scheduler for cmi!
Using step LR Scheduler for cchunk!
Using step LR Scheduler for lps!
Using step LR Scheduler for mfcc!
Using step LR Scheduler for prosody!
Use tenoserboard: True
pase(
  (frontend): WaveFe(
    (blocks): ModuleList(
      (0): FeBlock(
        (conv): SincConv_fast()
        (norm): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=64)
      )
      (1): FeBlock(
        (conv): Conv1d(64, 64, kernel_size=(20,), stride=(10,))
        (norm): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=64)
      )
      (2): FeBlock(
        (conv): Conv1d(64, 128, kernel_size=(11,), stride=(2,))
        (norm): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=128)
      )
      (3): FeBlock(
        (conv): Conv1d(128, 128, kernel_size=(11,), stride=(1,))
        (norm): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=128)
      )
      (4): FeBlock(
        (conv): Conv1d(128, 256, kernel_size=(11,), stride=(2,))
        (norm): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=256)
      )
      (5): FeBlock(
        (conv): Conv1d(256, 256, kernel_size=(11,), stride=(1,))
        (norm): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=256)
      )
      (6): FeBlock(
        (conv): Conv1d(256, 512, kernel_size=(11,), stride=(2,))
        (norm): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=512)
      )
      (7): FeBlock(
        (conv): Conv1d(512, 512, kernel_size=(11,), stride=(2,))
        (norm): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act): PReLU(num_parameters=512)
      )
    )
    (W): Conv1d(512, 100, kernel_size=(1,), stride=(1,))
    (norm_out): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
  )
  (regression_workers): ModuleList(
    (0): DecoderMinion(
      (blocks): ModuleList(
        (0): GDeconv1DBlock(
          (deconv): ConvTranspose1d(100, 512, kernel_size=(30,), stride=(4,), padding=(13,))
          (act): PReLU(num_parameters=512)
        )
        (1): GDeconv1DBlock(
          (deconv): ConvTranspose1d(512, 256, kernel_size=(30,), stride=(4,), padding=(13,))
          (act): PReLU(num_parameters=256)
        )
        (2): GDeconv1DBlock(
          (deconv): ConvTranspose1d(256, 128, kernel_size=(30,), stride=(10,), padding=(10,))
          (act): PReLU(num_parameters=128)
        )
        (3): MLPBlock(
          (W): Conv1d(128, 64, kernel_size=(1,), stride=(1,))
          (din): PatternedDropout()
          (act): PReLU(num_parameters=64)
          (dout): Dropout(p=0, inplace=False)
        )
      )
      (W): Conv1d(64, 1, kernel_size=(1,), stride=(1,))
    )
    (1): MLPMinion(
      (blocks): ModuleList(
        (0): MLPBlock(
          (W): Conv1d(100, 256, kernel_size=(1,), stride=(1,))
          (din): PatternedDropout()
          (act): PReLU(num_parameters=256)
          (dout): Dropout(p=0, inplace=False)
        )
      )
      (W): Conv1d(256, 1025, kernel_size=(1,), stride=(1,))
    )
    (2): MLPMinion(
      (blocks): ModuleList(
        (0): MLPBlock(
          (W): Conv1d(100, 256, kernel_size=(1,), stride=(1,))
          (din): PatternedDropout()
          (act): PReLU(num_parameters=256)
          (dout): Dropout(p=0, inplace=False)
        )
      )
      (W): Conv1d(256, 20, kernel_size=(1,), stride=(1,))
    )
    (3): MLPMinion(
      (blocks): ModuleList(
        (0): MLPBlock(
          (W): Conv1d(100, 256, kernel_size=(1,), stride=(1,))
          (din): PatternedDropout()
          (act): PReLU(num_parameters=256)
          (dout): Dropout(p=0, inplace=False)
        )
      )
      (W): Conv1d(256, 4, kernel_size=(1,), stride=(1,))
    )
  )
  (classification_workers): ModuleList(
    (0): SPC(
      (minion): SPCMinion(
        (blocks): ModuleList(
          (0): MLPBlock(
            (W): Conv1d(600, 256, kernel_size=(1,), stride=(1,))
            (din): PatternedDropout()
            (act): PReLU(num_parameters=256)
            (dout): Dropout(p=0, inplace=False)
          )
        )
        (W): Conv1d(256, 1, kernel_size=(1,), stride=(1,))
      )
    )
    (1): LIM(
      (minion): MLPMinion(
        (blocks): ModuleList(
          (0): MLPBlock(
            (W): Conv1d(200, 256, kernel_size=(1,), stride=(1,))
            (din): PatternedDropout()
            (act): PReLU(num_parameters=256)
            (dout): Dropout(p=0, inplace=False)
          )
        )
        (W): Conv1d(256, 1, kernel_size=(1,), stride=(1,))
      )
    )
    (2): GIM(
      (minion): MLPMinion(
        (blocks): ModuleList(
          (0): MLPBlock(
            (W): Conv1d(200, 256, kernel_size=(1,), stride=(1,))
            (din): PatternedDropout()
            (act): PReLU(num_parameters=256)
            (dout): Dropout(p=0, inplace=False)
          )
        )
        (W): Conv1d(256, 1, kernel_size=(1,), stride=(1,))
      )
    )
  )
)
----------
FeBlock(
  (conv): SincConv_fast()
  (norm): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=64)
)
Num params:  320
----------
----------
FeBlock(
  (conv): Conv1d(64, 64, kernel_size=(20,), stride=(10,))
  (norm): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=64)
)
Num params:  82176
----------
----------
FeBlock(
  (conv): Conv1d(64, 128, kernel_size=(11,), stride=(2,))
  (norm): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=128)
)
Num params:  90624
----------
----------
FeBlock(
  (conv): Conv1d(128, 128, kernel_size=(11,), stride=(1,))
  (norm): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=128)
)
Num params:  180736
----------
----------
FeBlock(
  (conv): Conv1d(128, 256, kernel_size=(11,), stride=(2,))
  (norm): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=256)
)
Num params:  361472
----------
----------
FeBlock(
  (conv): Conv1d(256, 256, kernel_size=(11,), stride=(1,))
  (norm): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=256)
)
Num params:  721920
----------
----------
FeBlock(
  (conv): Conv1d(256, 512, kernel_size=(11,), stride=(2,))
  (norm): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=512)
)
Num params:  1443840
----------
----------
FeBlock(
  (conv): Conv1d(512, 512, kernel_size=(11,), stride=(2,))
  (norm): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act): PReLU(num_parameters=512)
)
Num params:  2885632
----------
WaveFe total params: 5818020
Frontend params:  5818020
==================================================
Beginning training...
Batches per epoch:  12
Loss schedule policy: base
Reading latest checkpoint from pase_ckpt\PASE-checkpoints...
[!] No checkpoint found in pase_ckpt
################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Epoch 0/150:  17%|███████████████████████████████▏                                                                                                                                                           | 2/12 [00:59<05:07, 30.71s/it]################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Epoch 0/150:  33%|██████████████████████████████████████████████████████████████▎                                                                                                                            | 4/12 [02:12<04:22, 32.83s/it]################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Epoch 0/150:  50%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 6/12 [03:22<03:14, 32.43s/it]################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Epoch 0/150:  58%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150:  67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 8/12 [04:30<02:09, 32.30s/it]################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Epoch 0/150:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 10/12 [05:34<01:01, 30.88s/it]################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        ==================================================
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        Batch 12/12 (Epoch 0) step: 12:
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        spc, learning rate = 0.00050000, loss = 0.7067
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        mi, learning rate = 0.00050000, loss = 0.7009
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        cmi, learning rate = 0.00050000, loss = 0.7032
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        cchunk, learning rate = 0.00050000, loss = 0.1004
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        lps, learning rate = 0.00050000, loss = 32.5080
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        mfcc, learning rate = 0.00050000, loss = 28.9927
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        prosody, learning rate = 0.00050000, loss = 13.5776
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                        total, learning rate = 0.00050000, loss = 77.2894
Epoch 0/150:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████Epoch 0/150: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [06:36<00:00, 30.26s/it]
==================================================
Beginning evaluation...
################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Eval: 1/2:   0%|                                                                                 | 0/1 [00:00<?, ?it/s]################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

################################################################################
################################################################################

Traceback (most recent call last):
  File "E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master\pase\models\WorkerScheduler\trainer.py", line 295, in _eval
    batch = next(iterator)
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 465, in <module>
    train(opts)
  File "train.py", line 333, in train
    Trainer.train_(dloader, device=device, valid_dataloader=va_dloader)
  File "E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master\pase\models\WorkerScheduler\trainer.py", line 265, in train_
    device=device)
  File "E:\Python\Jupyter Notebook\ThaiSpeechEmotion\pase-master\pase\models\WorkerScheduler\trainer.py", line 298, in _eval
    batch = next(iterator)
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "E:\Anaconda3\envs\pase-master\lib\site-packages\torch\utils\data\dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration

**Comment by kame5** [comment]
![image](https://user-images.githubusercontent.com/48491704/99866317-e46ec500-2be2-11eb-8850-92c15a32d1eb.png)
![image](https://user-images.githubusercontent.com/48491704/99866327-08320b00-2be3-11eb-9e0b-0ccbde3eae40.png)
![image](https://user-images.githubusercontent.com/48491704/99866343-27309d00-2be3-11eb-91eb-313abbad93bd.png)
![image](https://user-images.githubusercontent.com/48491704/99866350-37e11300-2be3-11eb-8991-fb11a8f3edd6.png)
![image](https://user-images.githubusercontent.com/48491704/99866355-48918900-2be3-11eb-94c5-99ef1f7b6c9f.png)
![image](https://user-images.githubusercontent.com/48491704/99866402-737bdd00-2be3-11eb-8c5c-f45061b48cfd.png)
![image](https://user-images.githubusercontent.com/48491704/99866432-b2119780-2be3-11eb-9e48-58de1c6f1ce3.png)
![image](https://user-images.githubusercontent.com/48491704/99866441-c0f84a00-2be3-11eb-90d6-dac606360bb6.png)
![image](https://user-images.githubusercontent.com/48491704/99866457-d3728380-2be3-11eb-8a68-51a14e367356.png)

**Comment by Amforever** [comment]
Hello, how did you fix this problem, thanks. I used python3.6 and find the same problem
