### ISSUE TITLE
Retrain PASE with dataset of different sample rate wave files

### ISSUE THREAD

**Issue by lanhhv84** [santi-pdp/pase#80]
I am intending to retrain the PASE model with my collected dataset. However, my dataset is collected from different sources so it has different sample rates. After investigated your source code, I see that sometimes you load wave with native sample rate, sometimes resampled to 16000 Khz. Please tell me if I should modify the source code to always loading wave with 16000 Khz. Thanks you a lot

**Comment by santi-pdp** [comment]
Dear @lanhhv84 , perhaps it might be a better practice to go with a uniform 16k dataset, as we never worked with mixtures of sampling rates and do not the results it may raise. Nonetheless, the code should run straightaway even in the case of having mixtures of rates. Bear in mind that the time-window of the traning chunks for sampling rates > 16kHz will be smaller though, but perhaps that is not too important for you.

**Comment by lanhhv84** [comment]
Thanks you

**Comment by lanhhv84** [comment]
Dear @santi-pdp Should I modify the source code to hard-code sample rate to 16000

**Comment by santi-pdp** [comment]
That shouldn't be necessary. Do you mean you have an error?

**Comment by lanhhv84** [comment]
No it don't. I am just worrying about the final performance. And what about after training the model ?. You mean the model could work on arbitrary sample rate ?.

**Comment by santi-pdp** [comment]
That is an interesting research question for which we do not have an answer yet. But the model consumes waveforms, regardless of their sample rate. The only practical difference is the number of frames per second you obtain at the output (e.g. 100 frames/sec with 16kHz sampling). However, I would expect the model to face limitations with higher sampling rates, as there are new HF components it never saw during training. So perhaps it still works to analyze components below Nyquist freq but fails to get useful features for HF ranges (e.g. beyond 8kHz).
