### ISSUE TITLE
Fine tune the pre-trained weights

### ISSUE THREAD

**Issue by MittalShruti** [santi-pdp/pase#84]
Hey

I want to import the pre-trained weights and then fine tune on a **different language** speech data. The repo has steps to train the model from scratch. 

I want to fine-tune the already trained encoder-workers model on my speech data, so that I can get better features. Importing just the encoder as nn.Module, won't let me use the workers, and I won't be able to extract features the (self/)unsupervised learning way.

How should I do it?  

[EDIT] Also, e.g., I trained the PASE+ model on dataset1. Now after training, get more speech data for training (dataset2). In such a case, I would want to 'fine-tune' the model trained on dataset1, using this new dataset2. And not want to train from scratch on dataset2 + dataset1.

**Comment by pswietojanski** [comment]
Referencing the answer from #85, as its related: [https://github.com/santi-pdp/pase/issues/85#issuecomment-586909646](url)
